version: "3.9"
services:
  rabbitmq:
    build: ./rabbitmq/
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=P@ssw0rd
    ports:
          - "5672:5672"
          - "15672:15672"
  python_send:
    build: ./send/
    container_name: python_send
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
  python_receive:
    build: ./receive/
    container_name: python_receive
    depends_on:
      - python_send
    links:
      - python_send
    restart: on-failure

